### ISSUE TITLE
Try to use NFNet as backbone

### ISSUE THREAD

**Issue by taochx** [benjs/nfnets_pytorch#1]
Can NFNet be used as the backbone of some models like ResNet, such as UNet, and if so, what changes are needed?

**Comment by benjs** [comment]
You can replace your ResNet backbone with this network, you only need to adjust the number of classes in the final conv layer to your application and train it for a few epochs. 

I don't know UNet, but if it is a classifier network you can replace it too.

If you want only the last feature maps you can set the last linear layer to identity.

**Comment by benjs** [comment]
Closed due to no answer.
