### ISSUE TITLE
ModuleNotFoundError: No module named 'haiku'

### ISSUE THREAD

**Issue by rianusr** [benjs/nfnets_pytorch#5]
when i try "python3 eval.py --pretrained pretrained/F0_haiku.npz --dataset ***"
i got this error, have you ever met this error? how to fix this?

**Comment by benjs** [comment]
Install haiku:
```
pip install git+https://github.com/deepmind/dm-haiku
```

If that doesn't work, please post the complete stack trace.

**Comment by benjs** [comment]
Closed due to no answer.
